### ISSUE TITLE
AR (w/ linear)

### ISSUE THREAD

**Issue by tiagosalvador** [XJTU-XGU/Adversarial-Reweighting-for-Partial-Domain-Adaptation#1]
Hi,

First of all, thank you for sharing your code!

I tried to replicate the results for AR (w/linear) for Office-Home on the AC task. I did so by setting the variable normalize_classifier = False. However, I was only able to achieve 60.24% while the paper reports 62.13%. Are there any other changes I need to make to the code to achieve the reported accuracy?

Thanks!

**Comment by XJTU-XGU** [comment]
Thank you for your interest in our work. I think the difference maybe because of the random seed or environment.  I also suggest trying to set the bias of the classifer as false besides setting normalize_classifier = False.  By the way, I encourage using the full version with the SLR layer as the classifier.

**Comment by tiagosalvador** [comment]
I was using the same environment. Did not consider a different seed, since I was using the default one (2020). Tried with seed=2021 and got 61.37% and seed=2022 gave 62.45%. Thanks!
